services:
  - type: web
    name: eposrem-ui
    env: node
    plan: free
    rootDir: Interface
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
